import os
from pathlib import Path
import rasterio
from rasterio.enums import Resampling
import numpy as np

# Import OCM functions
from omnicloudmask import predict_from_load_func, load_s2


def replace_scl_mask_10m(original_scl_path, ocm_mask_path, output_path):
    """
    Takes the 10m OCM mask and the 20m SCL mask, merges them at 10m resolution,
    and applies the spatial nomenclature.
    """
    print(f"   Geomatic fusion in progress (10m Format)...")

    # 1. Open the OCM mask (10m) FIRST to retrieve ITS perfect geometry (10m)
    with rasterio.open(ocm_mask_path) as src_ocm:
        meta_10m = src_ocm.meta.copy()
        ocm_data = src_ocm.read(1)
        height, width = src_ocm.shape

    # 2. Open the original SCL (20m) and "inflate" it to the size of the OCM mask (10m) no problem we transform 1 pixel to 4 pixel
    with rasterio.open(original_scl_path) as src_scl:
        scl_data_10m = src_scl.read(
            1,
            out_shape=(height, width),
            resampling=Resampling.nearest 
        )

    # 3. Apply the transposition dictionary
    new_scl = np.copy(scl_data_10m)

    new_scl[ocm_data == 1] = 9   # Thick cloud -> High Probability Cloud
    new_scl[ocm_data == 2] = 10  # Thin cloud -> Cirrus
    new_scl[ocm_data == 3] = 3   # Shadow -> Shadow

    # 4. Save the new file
    if str(output_path).endswith('.jp2'):
        meta_10m.update(driver='JP2OpenJPEG')
    else:
        meta_10m.update(driver='GTiff', compress='lzw') 

    with rasterio.open(output_path, 'w', **meta_10m) as dest:
        dest.write(new_scl, 1)


# =====================================
# AUTOMATION: BATCH PROCESSING 
# =====================================
if __name__ == "__main__":
    
    # 1. .SAFE files folder
    input_folder = Path("/home/kheobs/Downloads/TEST OCM")
    
    # Final 10m masks folder
    final_output_folder = Path("/home/kheobs/Downloads/MASQUE OCM TEST")
    final_output_folder.mkdir(parents=True, exist_ok=True)

    # 2. Folder scanning
    safe_list = list(input_folder.glob("*.SAFE"))
    print(f"\n{len(safe_list)} .SAFE folders found in {input_folder}\n")
    print("-" * 50)

    # 3. Processing loop
    for index, safe_path in enumerate(safe_list, start=1):
        print(f"[{index}/{len(safe_list)}] Processing: {safe_path.name}")
        
        try:
            # STEP A: OCM mask generation 
            print("   Launching OmniCloudMask AI...")
            ocm_result_paths = predict_from_load_func([safe_path], load_s2)
            ocm_mask_path = ocm_result_paths[0] # Path to the raw .tif generated by OCM
            
            # STEP B: Automatic search for the 20m SCL mask in the .SAFE ---
            scl_search = list(safe_path.glob("GRANULE/*/IMG_DATA/R20m/*_SCL_20m.jp2"))
            
            if not scl_search:
                raise FileNotFoundError("Unable to find the SCL_20m.jp2 mask in this SAFE folder.")
                
            original_scl_path = scl_search[0]

            # --- STEP C: Defining the final file name ---
            original_scl_name = original_scl_path.stem
            scl_10m_name = original_scl_name.replace("20m", "10m") 
            final_file_name = f"{scl_10m_name}_HYBRID.jp2"           
            hybrid_output_path = final_output_folder / final_file_name

            # STEP D: Mask replacement
            replace_scl_mask_10m(original_scl_path, ocm_mask_path, hybrid_output_path)
            
            print(f"   Success! Saved here: {hybrid_output_path}\n")
            
        except Exception as e:
            print(f"   Error on {safe_path.name}: {e}\n")

    print("-" * 50)
    print("All your files are ready.")
